name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            spec: specs/linux.spec
            upload_exe_with_name: 'WigglegramCreator-linux-x64'
          - os: windows-latest
            spec: specs/windows.spec
            upload_exe_with_name: 'WigglegramCreator-windows-x64'
          - os: macos-latest
            spec: specs/macos.spec
            upload_exe_with_name: 'WigglegramCreator-macos-x64'

    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: '${{ matrix.spec }}'
          requirements: 'requirements.txt'
          upload_exe_with_name: '${{ matrix.upload_exe_with_name }}'
