name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: create_wiggle
            icon: icons/icon-512.png
            options: --noconsole --onefile --icon=icons/icon-512.png
          - os: windows-latest
            artifact_name: create_wiggle.exe
            icon: icons/icon_512_tIf_icon.ico
            options: --noconsole --onefile --icon=icons/icon_512_tIf_icon.ico
          - os: macos-latest
            artifact_name: WigglegramCreator.app.zip
            icon: icons/icon-512.png
            options: --windowed --name "WigglegramCreator" --icon=icons/icon.icns

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          requirements: 'requirements.txt'
          options: ${{ matrix.options }}
          upload_exe_with_name: ${{ matrix.artifact_name }}
          spec: ''  # Optionally specify your .spec file if you have one

      - name: Zip macOS .app bundle
        if: matrix.os == 'macos-latest'
        run: |
          cd dist
          zip -r WigglegramCreator.app.zip WigglegramCreator.app

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}