name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux x64
          - os: ubuntu-latest
            arch: 'x64'
            spec: specs/linux.spec
          # Linux arm64 (public preview)
          - os: ubuntu-24.04-arm
            arch: 'arm64'
            spec: specs/linux.spec
          # Windows x64
          - os: windows-latest
            arch: 'x64'
            spec: specs/windows.spec
          # Windows arm64 (public preview)
          - os: windows-11-arm
            arch: 'arm64'
            spec: specs/windows.spec
          # macOS x64 (Intel)
          - os: macos-13
            arch: 'x64'
            spec: specs/macos.spec
          # macOS arm64 (Apple Silicon)
          - os: macos-latest
            arch: 'arm64'
            spec: specs/macos.spec
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller ${{ matrix.spec }}

      - name: Zip build output
        run: |
          cd dist
          zip -r ../wigglegram-creator-${{ runner.os }}-${{ matrix.arch }}.zip .
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wigglegram-creator-${{ runner.os }}-${{ matrix.arch }}
          path: wigglegram-creator-${{ runner.os }}-${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
