name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (for ARM)
        if: matrix.arch == 'arm64' && matrix.os != 'macos-latest'
        uses: docker/setup-qemu-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv (all platforms)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          uv pip install . --system

      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          if [ "$RUNNER_OS" = "Windows" ]; then
            pyinstaller --noconsole --onefile --icon=icons/icon_512_tIf_icon.ico create_wiggle.py
          elif [ "$RUNNER_OS" = "macOS" ]; then
            # Build .app bundle and zip it
            pyinstaller --windowed --name "WigglegramCreator-${{ matrix.arch }}" --icon=icons/icon-512.png create_wiggle.py
            cd dist
            zip -r "WigglegramCreator-${{ matrix.arch }}.zip" "WigglegramCreator-${{ matrix.arch }}.app"
            cd ..
          else
            pyinstaller --noconsole --onefile --icon=icons/icon-512.png create_wiggle.py
          fi

      - name: Archive binaries (Windows/Linux)
        if: runner.os != 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: wigglegram-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*

      - name: Archive macOS .app zip
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: wigglegram-macos-${{ matrix.arch }}
          path: dist/WigglegramCreator-${{ matrix.arch }}.zip
