name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python_arch: 'x64'
            spec: specs/linux.spec
            upload_exe_with_name: 'WigglegramCreator'
          - os: windows-latest
            python_arch: 'x64'
            spec: specs/windows.spec
          - os: macos-latest
            python_arch: 'x64'
            spec: specs/macos.spec
          - os: ubuntu-latest
            python_arch: 'arm64'
            spec: specs/linux.spec
          - os: windows-latest
            python_arch: 'arm64'
            spec: specs/windows.spec
          - os: macos-latest
            python_arch: 'arm64'
            spec: specs/macos.spec

    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          python_arch: ${{ matrix.python_arch }}
          spec: '${{ matrix.spec }}'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'WigglegramCreator'
          options: '--onefile'
