name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: create_wiggle
            spec: specs/linux.spec
          - os: windows-latest
            artifact_name: create_wiggle.exe
            spec: specs/windows.spec
          - os: macos-latest
            artifact_name: WigglegramCreator.app.zip
            spec: specs/macos.spec

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          requirements: 'requirements.txt'
          upload_exe_with_name: ${{ matrix.artifact_name }}
          spec: ${{ matrix.spec }}

      - name: Zip build output (Linux/Windows)
        if: matrix.os != 'macos-latest'
        run: |
          cd dist
          zip -r ${{ matrix.artifact_name }} ${artifact_name%.*}
        shell: bash

      - name: Zip macOS .app bundle
        if: matrix.os == 'macos-latest'
        run: |
          cd dist
          zip -r WigglegramCreator.app.zip WigglegramCreator.app

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}