name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU (for ARM)
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          uv pip install . --system
      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          if [ "$RUNNER_OS" = "Windows" ]; then
            pyinstaller --noconsole --onefile --icon=icon_512_tIf_icon.ico create_wiggle.py
          else
            pyinstaller --noconsole --onefile --icon=icon-512.png create_wiggle.py
          fi
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: wigglegram-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*
