name: Build and Release macOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-macos-app:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Homebrew dependencies
        run: |
          brew install uv

      - name: Install Python dependencies
        run: |
          uv pip install .

      - name: Install PyInstaller
        run: |
          uv pip install pyinstaller

      - name: Build macOS app with PyInstaller
        run: |
          # Set ARCHFLAGS to build for the selected architecture
          export ARCHFLAGS="-arch ${{ matrix.arch }}"
          pyinstaller --windowed --name "WigglegramCreator-${{ matrix.arch }}" --icon=icon.icns create_wiggle.py

      - name: Archive app for release
        run: |
          cd dist
          zip -r WigglegramCreator-${{ matrix.arch }}.zip WigglegramCreator-${{ matrix.arch }}.app

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/WigglegramCreator-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

